#include "world/grammar.hpp"
#include <algorithm>
#include <sstream>
#include <queue>

#include "core/rng.hpp"

namespace eidolon {

GrammarDerivation GrammarEngine::derive(int maxSteps) const {
  GrammarDerivation result;
  std::string current = grammar_.startSymbol;
  result.result = current;
  result.steps.push_back(current);

  for (int step = 0; step < maxSteps; ++step) {
    // Find first non-terminal in current string
    size_t ntStart = current.find('<');
    if (ntStart == std::string::npos) break; // fully expanded

    size_t ntEnd = current.find('>', ntStart);
    if (ntEnd == std::string::npos) break;

    std::string nt = current.substr(ntStart + 1, ntEnd - ntStart - 1);

    // Find first production for this non-terminal
    auto it = grammar_.lhsIndex.find(nt);
    if (it == grammar_.lhsIndex.end() || it->second.empty()) break;

    size_t prodIdx = it->second[0]; // deterministic: first production
    const auto& prod = grammar_.productions[prodIdx];

    // Build RHS string
    std::string rhsStr;
    for (const auto& sym : prod.rhs) {
      if (sym.isTerminal) {
        rhsStr += sym.value;
      } else {
        rhsStr += "<" + sym.value + ">";
      }
    }

    // Replace non-terminal with RHS
    current.replace(ntStart, ntEnd - ntStart + 1, rhsStr);
    result.result = current;
    result.steps.push_back(current);
    result.appliedRules.emplace_back(prod.lhs, rhsStr);
  }
  return result;
}

GrammarDerivation GrammarEngine::deriveStochastic(class Rng& rng, int maxSteps) const {
  GrammarDerivation result;
  std::string current = grammar_.startSymbol;
  result.result = current;
  result.steps.push_back(current);

  for (int step = 0; step < maxSteps; ++step) {
    size_t ntStart = current.find('<');
    if (ntStart == std::string::npos) break;

    size_t ntEnd = current.find('>', ntStart);
    if (ntEnd == std::string::npos) break;

    std::string nt = current.substr(ntStart + 1, ntEnd - ntStart - 1);

    auto it = grammar_.lhsIndex.find(nt);
    if (it == grammar_.lhsIndex.end() || it->second.empty()) break;

    // Stochastic selection based on weights
    const auto& prodIndices = it->second;
    float totalWeight = 0.0f;
    for (size_t idx : prodIndices) totalWeight += grammar_.productions[idx].weight;

    float r = static_cast<float>(rng.range(0.0, static_cast<double>(totalWeight)));
    float cum = 0.0f;
    size_t chosenIdx = prodIndices.back();
    for (size_t idx : prodIndices) {
      cum += grammar_.productions[idx].weight;
      if (r <= cum) { chosenIdx = idx; break; }
    }

    const auto& prod = grammar_.productions[chosenIdx];

    std::string rhsStr;
    for (const auto& sym : prod.rhs) {
      if (sym.isTerminal) rhsStr += sym.value;
      else rhsStr += "<" + sym.value + ">";
    }

    current.replace(ntStart, ntEnd - ntStart + 1, rhsStr);
    result.result = current;
    result.steps.push_back(current);
    result.appliedRules.emplace_back(prod.lhs, rhsStr);
  }
  return result;
}

bool GrammarEngine::parse(const std::string& str) const {
  // Simplified: check if the string can be generated by the grammar
  // For now, just check if we can derive the exact string
  auto derivation = derive(100);
  return derivation.result == str;
}

std::vector<std::vector<GrammarSymbol>> GrammarEngine::getExpansions(const std::string& nonTerminal) const {
  auto it = grammar_.lhsIndex.find(nonTerminal);
  if (it == grammar_.lhsIndex.end()) return {};
  std::vector<std::vector<GrammarSymbol>> result;
  for (size_t idx : it->second) {
    result.push_back(grammar_.productions[idx].rhs);
  }
  return result;
}

// Predefined grammars

Grammar makeGoalGrammar() {
  Grammar g;
  g.startSymbol = "ROOT";
  g.productions = {
    // ROOT -> goal templates
    {"ROOT", {GrammarSymbol::terminal("Goal: "), GrammarSymbol::nonTerminal("GOAL_TYPE"), GrammarSymbol::terminal(" at "), GrammarSymbol::nonTerminal("LOCATION"), GrammarSymbol::terminal(" by "), GrammarSymbol::nonTerminal("TIMEFRAME")}, 1.0f},

    // GOAL_TYPE
    {"GOAL_TYPE", {GrammarSymbol::terminal("find food")}, 0.3f},
    {"GOAL_TYPE", {GrammarSymbol::terminal("find water")}, 0.2f},
    {"GOAL_TYPE", {GrammarSymbol::terminal("build shelter")}, 0.15f},
    {"GOAL_TYPE", {GrammarSymbol::terminal("explore new area")}, 0.15f},
    {"GOAL_TYPE", {GrammarSymbol::terminal("hunt prey")}, 0.1f},
    {"GOAL_TYPE", {GrammarSymbol::terminal("craft tool")}, 0.1f},

    // LOCATION
    {"LOCATION", {GrammarSymbol::terminal("nearby")}, 0.4f},
    {"LOCATION", {GrammarSymbol::terminal("in the forest")}, 0.2f},
    {"LOCATION", {GrammarSymbol::terminal("by the river")}, 0.2f},
    {"LOCATION", {GrammarSymbol::terminal("at the ruins")}, 0.1f},
    {"LOCATION", {GrammarSymbol::terminal("in the valley")}, 0.1f},

    // TIMEFRAME
    {"TIMEFRAME", {GrammarSymbol::terminal("today")}, 0.5f},
    {"TIMEFRAME", {GrammarSymbol::terminal("this week")}, 0.3f},
    {"TIMEFRAME", {GrammarSymbol::terminal("before nightfall")}, 0.2f},
  };
  return g;
}

Grammar makeEventGrammar() {
  Grammar g;
  g.startSymbol = "ROOT";
  g.productions = {
    {"ROOT", {GrammarSymbol::terminal("Event: "), GrammarSymbol::nonTerminal("EVENT_TYPE"), GrammarSymbol::terminal(" at "), GrammarSymbol::nonTerminal("LOCATION"), GrammarSymbol::terminal(" - "), GrammarSymbol::nonTerminal("OUTCOME")}, 1.0f},

    {"EVENT_TYPE", {GrammarSymbol::terminal("found food")}, 0.25f},
    {"EVENT_TYPE", {GrammarSymbol::terminal("found water")}, 0.2f},
    {"EVENT_TYPE", {GrammarSymbol::terminal("encountered predator")}, 0.15f},
    {"EVENT_TYPE", {GrammarSymbol::terminal("built shelter")}, 0.1f},
    {"EVENT_TYPE", {GrammarSymbol::terminal("crafted tool")}, 0.1f},
    {"EVENT_TYPE", {GrammarSymbol::terminal("discovered landmark")}, 0.1f},
    {"EVENT_TYPE", {GrammarSymbol::terminal("slept")}, 0.1f},

    {"LOCATION", {GrammarSymbol::terminal("home")}, 0.3f},
    {"LOCATION", {GrammarSymbol::terminal("forest")}, 0.2f},
    {"LOCATION", {GrammarSymbol::terminal("river")}, 0.2f},
    {"LOCATION", {GrammarSymbol::terminal("ruins")}, 0.15f},
    {"LOCATION", {GrammarSymbol::terminal("cave")}, 0.15f},

    {"OUTCOME", {GrammarSymbol::terminal("success")}, 0.6f},
    {"OUTCOME", {GrammarSymbol::terminal("partial success")}, 0.25f},
    {"OUTCOME", {GrammarSymbol::terminal("failure")}, 0.15f},
  };
  return g;
}

Grammar makeRecipeGrammar() {
  Grammar g;
  g.startSymbol = "ROOT";
  g.productions = {
    {"ROOT", {GrammarSymbol::nonTerminal("RECIPE")}, 1.0f},

    {"RECIPE", {GrammarSymbol::terminal("Recipe: "), GrammarSymbol::nonTerminal("ITEM"), GrammarSymbol::terminal(" = "), GrammarSymbol::nonTerminal("INGREDIENTS"), GrammarSymbol::terminal(" -> "), GrammarSymbol::nonTerminal("RESULT")}, 1.0f},

    {"ITEM", {GrammarSymbol::terminal("stone axe")}, 0.2f},
    {"ITEM", {GrammarSymbol::terminal("stone knife")}, 0.2f},
    {"ITEM", {GrammarSymbol::terminal("spear")}, 0.15f},
    {"ITEM", {GrammarSymbol::terminal("fire")}, 0.2f},
    {"ITEM", {GrammarSymbol::terminal("shelter")}, 0.15f},
    {"ITEM", {GrammarSymbol::terminal("rope")}, 0.1f},

    {"INGREDIENTS", {GrammarSymbol::nonTerminal("MATERIAL"), GrammarSymbol::terminal(" + "), GrammarSymbol::nonTerminal("MATERIAL")}, 0.7f},
    {"INGREDIENTS", {GrammarSymbol::nonTerminal("MATERIAL")}, 0.3f},

    {"MATERIAL", {GrammarSymbol::terminal("stone")}, 0.3f},
    {"MATERIAL", {GrammarSymbol::terminal("wood")}, 0.3f},
    {"MATERIAL", {GrammarSymbol::terminal("vine")}, 0.2f},
    {"MATERIAL", {GrammarSymbol::terminal("bone")}, 0.1f},
    {"MATERIAL", {GrammarSymbol::terminal("hide")}, 0.1f},

    {"RESULT", {GrammarSymbol::terminal("tool")}, 0.4f},
    {"RESULT", {GrammarSymbol::terminal("weapon")}, 0.3f},
    {"RESULT", {GrammarSymbol::terminal("shelter")}, 0.2f},
    {"RESULT", {GrammarSymbol::terminal("consumable")}, 0.1f},
  };
  return g;
}

Grammar makeUtteranceGrammar() {
  Grammar g;
  g.startSymbol = "ROOT";
  g.productions = {
    {"ROOT", {GrammarSymbol::nonTerminal("UTTERANCE")}, 1.0f},

    {"UTTERANCE", {GrammarSymbol::nonTerminal("GREETING"), GrammarSymbol::terminal(" "), GrammarSymbol::nonTerminal("STATEMENT")}, 0.4f},
    {"UTTERANCE", {GrammarSymbol::nonTerminal("STATEMENT")}, 0.4f},
    {"UTTERANCE", {GrammarSymbol::nonTerminal("QUESTION")}, 0.2f},

    {"GREETING", {GrammarSymbol::terminal("Hello")}, 0.3f},
    {"GREETING", {GrammarSymbol::terminal("Hi")}, 0.3f},
    {"GREETING", {GrammarSymbol::terminal("Greetings")}, 0.2f},
    {"GREETING", {GrammarSymbol::terminal("Hey")}, 0.2f},

    {"STATEMENT", {GrammarSymbol::terminal("I am "), GrammarSymbol::nonTerminal("STATE")}, 0.3f},
    {"STATEMENT", {GrammarSymbol::terminal("I need "), GrammarSymbol::nonTerminal("NEED")}, 0.3f},
    {"STATEMENT", {GrammarSymbol::terminal("I found "), GrammarSymbol::nonTerminal("FIND")}, 0.2f},
    {"STATEMENT", {GrammarSymbol::terminal("The "), GrammarSymbol::nonTerminal("OBSERVATION")}, 0.2f},

    {"STATE", {GrammarSymbol::terminal("hungry")}, 0.25f},
    {"STATE", {GrammarSymbol::terminal("thirsty")}, 0.25f},
    {"STATE", {GrammarSymbol::terminal("tired")}, 0.2f},
    {"STATE", {GrammarSymbol::terminal("well")}, 0.3f},

    {"NEED", {GrammarSymbol::terminal("food")}, 0.35f},
    {"NEED", {GrammarSymbol::terminal("water")}, 0.35f},
    {"NEED", {GrammarSymbol::terminal("rest")}, 0.15f},
    {"NEED", {GrammarSymbol::terminal("shelter")}, 0.15f},

    {"FIND", {GrammarSymbol::terminal("food")}, 0.3f},
    {"FIND", {GrammarSymbol::terminal("water")}, 0.3f},
    {"FIND", {GrammarSymbol::terminal("a landmark")}, 0.2f},
    {"FIND", {GrammarSymbol::terminal("a ruin")}, 0.2f},

    {"OBSERVATION", {GrammarSymbol::terminal("weather is nice")}, 0.2f},
    {"OBSERVATION", {GrammarSymbol::terminal("animals are nearby")}, 0.2f},
    {"OBSERVATION", {GrammarSymbol::terminal("plants are blooming")}, 0.2f},
    {"OBSERVATION", {GrammarSymbol::terminal("it will rain soon")}, 0.2f},
    {"OBSERVATION", {GrammarSymbol::terminal("the river is high")}, 0.2f},

    {"QUESTION", {GrammarSymbol::terminal("Where is "), GrammarSymbol::nonTerminal("THING"), GrammarSymbol::terminal("?")}, 0.5f},
    {"QUESTION", {GrammarSymbol::terminal("How do I "), GrammarSymbol::nonTerminal("ACTION"), GrammarSymbol::terminal("?")}, 0.5f},

    {"THING", {GrammarSymbol::terminal("food")}, 0.3f},
    {"THING", {GrammarSymbol::terminal("water")}, 0.3f},
    {"THING", {GrammarSymbol::terminal("shelter")}, 0.2f},
    {"THING", {GrammarSymbol::terminal("the ruins")}, 0.2f},

    {"ACTION", {GrammarSymbol::terminal("make fire")}, 0.3f},
    {"ACTION", {GrammarSymbol::terminal("build shelter")}, 0.3f},
    {"ACTION", {GrammarSymbol::terminal("craft a tool")}, 0.2f},
    {"ACTION", {GrammarSymbol::terminal("hunt")}, 0.2f},
  };
  return g;
}

} // namespace eidolon